### ISSUE TITLE
ES caps total hits at 10K?

### ISSUE THREAD

**Issue by philbudne** [mediacloud/news-search-api#26]
It looks like https://github.com/mediacloud/story-indexer/issues/166 is an ES query API issue, so opening issue here.

**Comment by philbudne** [comment]
Summary: To get real total hits, you now need to set a (possibly expensive) parameter `track_total_hits`:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html#track-total-hits

@rahulbot asked:
> Ugh. That's ridiculous (from a database user perspective). This is critical data we need to show users on every search result. Could we:
> a. sum the attention-over-time data and use that to provide an estimated total? (Django front-end server could do this, or mediacloud-news-search library used by mc-providers)
> b. turn on the expensive solution in staging and measure true impact on our data?

**Comment by philbudne** [comment]
The "b." alternative begs a question: how best to develop/test news-search-api, which I've created this issue for: https://github.com/mediacloud/news-search-api/issues/27

**Comment by pgulley** [comment]
Sorry- I missed this thread. I've just gone ahead and added the track_total_hits parameter to the overview query. I'll ping IA tomorrow to see how they addressed this issue in their system, but I figure we can play with this for now.

**Comment by pgulley** [comment]
Yes! Closing
